name: DS5111 su24 package tester

on:
  workflow_dispatch:
    inputs:
      uuid:
        desciption: "Virginia uuid"
        default: ""
        required: true
        type: string
      github-id:
        description: "Github handle"
        default: ""
        required: true
        type: string
      package-name:
        description: "Name of package after pip install"
        default: ""
        required: true
        type: string
  

permissions:
  id-token: write
  contents: read
  pull-requests: write
  
jobs:
  validate-package:
    name: Validate Installable Package
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    defaults:
      run:
        shell: bash
    steps:
    - name: Create env, install package, test package import 
      env:
        GHANDLE: ${{ inputs.github-id }}
        VID: ${{ inputs.uuid }}
        PACKAGE: ${{ inputs.package-name }}
      run: |
        python3 -m venv env; . env/bin/activate; pip install --upgrade pip
        . env/bin/activate; pip install git+https://github.com/${GHANDLE}/${VID}_DS5111su24_lab_01@final_review
        . env/bin/activate; pip list
        . env/bin/activate; python -c "import ${PACKAGE} as pkg; print(pkg.tokenize('To be or not to be'))"

